---
# Source: mediawiki/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locawiki-mediawiki
  namespace: "locawiki"
  labels:
    app.kubernetes.io/instance: locawiki
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/version: 1.41.1
    helm.sh/chart: mediawiki-20.2.6
spec:
  replicas: 1            
  selector:
    matchLabels:
      app.kubernetes.io/instance: locawiki
      app.kubernetes.io/name: mediawiki
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: locawiki
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mediawiki
        app.kubernetes.io/version: 1.41.1
        helm.sh/chart: mediawiki-20.2.6
    spec:
      
      serviceAccountName: locawiki-mediawiki
      automountServiceAccountToken: false
      # yamllint disable rule:indentation
      hostAliases:
        - hostnames:
          - status.localhost
          ip: 127.0.0.1
      # yamllint enable rule:indentation
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: locawiki
                    app.kubernetes.io/name: mediawiki
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      priorityClassName: ""
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      initContainers:
        - name: prepare-base-dir
          image: docker.io/bitnami/mediawiki:1.41.1-debian-12-r9
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              cpu: 375m
              ephemeral-storage: 1024Mi
              memory: 384Mi
            requests:
              cpu: 250m
              ephemeral-storage: 50Mi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          command:
            - /bin/bash
          args:
            - -ec
            - |
              #!/bin/bash

              . /opt/bitnami/scripts/liblog.sh
              . /opt/bitnami/scripts/libfs.sh

              info "Copying base dir to empty dir"
              # In order to not break the application functionality (such as upgrades or plugins) we need
              # to make the base directory writable, so we need to copy it to an empty dir volume
              cp -r --preserve=mode /opt/bitnami/mediawiki /emptydir/app-base-dir

              info "Copying symlinks to stdout/stderr"
              # We copy the logs folder because it has symlinks to stdout and stderr
              if ! is_dir_empty /opt/bitnami/apache/logs; then
                cp -r /opt/bitnami/apache/logs /emptydir/apache-logs-dir
              fi
              info "Copy operation completed"
          volumeMounts:
            - name: empty-dir
              mountPath: /emptydir
      containers:
        - name: locawiki-mediawiki
          image: docker.io/bitnami/mediawiki:1.41.1-debian-12-r9
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MARIADB_HOST
              value: "locawiki-mariadb"
            - name: MARIADB_PORT_NUMBER
              value: "3306"
            - name: MEDIAWIKI_DATABASE_NAME
              value: "bitnami_mediawiki"
            - name: MEDIAWIKI_DATABASE_USER
              value: "bn_mediawiki"
            - name: MEDIAWIKI_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: locawiki-mariadb
                  key: mariadb-password
            - name: MEDIAWIKI_HOST
              value: "locawiki"
            - name: MEDIAWIKI_USERNAME
              value: "user"
            - name: MEDIAWIKI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: locawiki-mediawiki
                  key: mediawiki-password
            - name: MEDIAWIKI_EMAIL
              value: "user@example.com"
            - name: MEDIAWIKI_WIKI_NAME
              value: "My Wiki"
            - name: APACHE_HTTP_PORT_NUMBER
              value: "8080"
            - name: APACHE_HTTPS_PORT_NUMBER
              value: "8443"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 5
          # readinessProbe:
          #   failureThreshold: 6
          #   httpGet:
          #     httpHeaders:
          #     - name: Host
          #       value: 'locawiki'
          #     path: /api.php?action=query&meta=siteinfo&format=none
          #     port: http
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 5
          resources:
            limits:
              cpu: 375m
              ephemeral-storage: 1024Mi
              memory: 384Mi
            requests:
              cpu: 250m
              ephemeral-storage: 50Mi
              memory: 256Mi
          volumeMounts:
            - name: empty-dir
              mountPath: /opt/bitnami/apache/conf
              subPath: apache-conf-dir
            - name: empty-dir
              mountPath: /opt/bitnami/apache/logs
              subPath: apache-logs-dir
            - name: empty-dir
              mountPath: /opt/bitnami/apache/var/run
              subPath: apache-tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/php/etc
              subPath: php-conf-dir
            - name: empty-dir
              mountPath: /opt/bitnami/php/tmp
              subPath: php-tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/php/var
              subPath: php-var-dir
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/mediawiki
              subPath: app-base-dir
            - mountPath: /bitnami/mediawiki
              name: mediawiki-data
              subPath: mediawiki
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: mediawiki-data
          persistentVolumeClaim:
            claimName: locawiki-mediawiki-mediawiki
