---
# Source: mediawiki/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: locawiki-mediawiki
  namespace: "locawiki"
  labels:
    app.kubernetes.io/instance: locawiki
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/version: 1.41.1
type: Opaque
data:
  mediawiki-password: "NXNkS1hBaHBGQg=="
