---
# Source: mediawiki/charts/mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: locawiki-mariadb
  namespace: "locawiki"
  labels:
    app.kubernetes.io/instance: locawiki
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 11.3.2
automountServiceAccountToken: false
---
# Source: mediawiki/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: locawiki-mediawiki
  namespace: "locawiki"
  labels:
    app.kubernetes.io/instance: locawiki
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/version: 1.41.1
automountServiceAccountToken: false
